from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views
from rest_framework.authtoken.views import obtain_auth_token
from django.urls import path

# Set up the router for the BookViewSet (use BookViewSet instead of BookList)
router = DefaultRouter()
router.register(r'books', views.BookViewSet, basename='book-list')  # Register BookViewSet

# Define the urlpatterns for the API
urlpatterns = [

    path('books/', views.BookList.as_view(), name='book-list'),  # Optional: Keep for specific list view
    path('', include(router.urls)),  # Include the routes generated by the 
]


